export const GET_SHELVES = 'GET_SHELVES';
export const GET_SHELVES_ERROR = 'GET_SHELVES_ERROR';
export const GET_SINGLE_SHELF = 'GET_SINGLE_SHELF';
export const GET_SINGLE_SHELF_ERROR = 'GET_SINGLE_SHELF_ERROR';
export const GET_SINGLE_BOOK = 'GET_SINGLE_BOOK';
export const GET_SINGLE_BOOK_ERROR = 'GET_SINGLE_BOOK_ERROR';
